# Nasal Data

### Loaading and Saving

In [15]:
import anndata as ad
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
raw_nasal = ad.read_h5ad("/Users/nathan/Desktop/Camplab/Cellxgene/CellxgeneCorrectNasal/CxG_raw_nose_integrated_20210315_dim30_labeled.h5ad")
raw_nasal

AnnData object with n_obs × n_vars = 34833 × 33694
    obs: 'donor_id', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'integrated_snn_res.1.2', 'seurat_clusters', 'cell_type', 'age', 'smoking_status', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'cell_type_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'assay_ontology_term_id', 'suspension_type', 'is_primary_data', 'organism_ontology_term_id'
    var: 'features', 'feature_is_filtered'
    uns: 'PCs', 'pca_stdev', 'title'
    obsm: 'X_pca', 'X_umap'
    obsp: 'nn', 'snn'

In [11]:
if 'feature_is_filtered' not in raw_nasal.var.columns:
    raw_nasal.var['feature_is_filtered'] = False 

In [8]:
if 'X_pca' in raw_nasal.obsm:
    raw_nasal.obsm['X_pca'] = raw_nasal.obsm['X_pca'].values

In [11]:
raw_nasal.write('CxG_raw_nose_integrated_20210315_dim30_labeled.h5ad')

In [123]:
raw_nasal.__dict__['_raw'].__dict__['_var'] = raw_nasal.__dict__['_raw'].__dict__['_var'].rename(columns={'_index': 'features'})

In [126]:
raw_nasal.uns['title'] = 'Nasal scRNA-Seq Dataset'

## Count data

Var expects dataframe, remember!!!

Checking raw count data

In [127]:
dense = raw_nasal.X.toarray()
print(dense)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 1.35780992 0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.34601806 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


Checking count matrices

## Metadata

Let's check the metadata for the nasal object

In [16]:
raw_nasal.obs

donor_id  nCount_RNA  nFeature_RNA  percent.mt  \
AAACCTGAGAGCCTAG               BU_L1      1604.0           732    7.481297   
AAACCTGAGATCGATA               BU_L1      5782.0          1898    8.353511   
AAACCTGAGCGATATA               BU_L1      3463.0          1390    8.489749   
AAACCTGAGCGTCAAG               BU_L1      1946.0           825    5.395683   
AAACCTGAGCTGATAA               BU_L1      1685.0           922    9.673591   
...                              ...         ...           ...         ...   
TTCTTAGGTCATATGC  LH_1925_cellRanger     29369.0          5368    4.780551   
TTGCGTCGTGATAAGT  LH_1925_cellRanger      5279.0          1708    2.292101   
TTGCGTCTCTCGCATC  LH_1925_cellRanger     25460.0          4282    0.816968   
TTGTAGGGTTACGACT  LH_1925_cellRanger     24188.0          5258    2.947743   
TTTGGTTTCGCCATAA  LH_1925_cellRanger     18904.0          4039    2.020736   

                  integrated_snn_res.1.2  seurat_clusters  \
AAACCTGAGAGCCTAG                       1                1   
AAACCTGAGATCGATA                       1                1   
AAACCTGAGCGATATA                       9                9   
AAACCTGAGCGTCAAG                       2                2   
AAACCTGAGCTGATAA                       1                1   
...                                  ...              ...   
TTCTTAGGTCATATGC                       0                0   
TTGCGTCGTGATAAGT                       1                1   
TTGCGTCTCTCGCATC                      12               12   
TTGTAGGGTTACGACT                       0                0   
TTTGGTTTCGCCATAA                       9                9   

                                          cell_type age smoking_status  \
AAACCTGAGAGCCTAG          Olfactory glandular cells  30          Never   
AAACCTGAGATCGATA          Olfactory glandular cells  30          Never   
AAACCTGAGCGATATA      Transitional Cells_Basal_Club  30          Never   
AAACCTGAGCGTCAAG  Transitional Cells_Club_Secretory  30          Never   
AAACCTGAGCTGATAA          Olfactory glandular cells  30          Never   
...                                             ...  ..            ...   
TTCTTAGGTCATATGC                       Goblet cells  59        Current   
TTGCGTCGTGATAAGT          Olfactory glandular cells  59        Current   
TTGCGTCTCTCGCATC                        Basal cells  59        Current   
TTGTAGGGTTACGACT                       Goblet cells  59        Current   
TTTGGTTTCGCCATAA      Transitional Cells_Basal_Club  59        Current   

                 development_stage_ontology_term_id sex_ontology_term_id  \
AAACCTGAGAGCCTAG                     HsapDv:0000124         PATO:0000384   
AAACCTGAGATCGATA                     HsapDv:0000124         PATO:0000384   
AAACCTGAGCGATATA                     HsapDv:0000124         PATO:0000384   
AAACCTGAGCGTCAAG                     HsapDv:0000124         PATO:0000384   
AAACCTGAGCTGATAA                     HsapDv:0000124         PATO:0000384   
...                                             ...                  ...   
TTCTTAGGTCATATGC                     HsapDv:0000153         PATO:0000384   
TTGCGTCGTGATAAGT                     HsapDv:0000153         PATO:0000384   
TTGCGTCTCTCGCATC                     HsapDv:0000153         PATO:0000384   
TTGTAGGGTTACGACT                     HsapDv:0000153         PATO:0000384   
TTTGGTTTCGCCATAA                     HsapDv:0000153         PATO:0000384   

                 self_reported_ethnicity_ontology_term_id  \
AAACCTGAGAGCCTAG                           HANCESTRO:0590   
AAACCTGAGATCGATA                           HANCESTRO:0590   
AAACCTGAGCGATATA                           HANCESTRO:0590   
AAACCTGAGCGTCAAG                           HANCESTRO:0590   
AAACCTGAGCTGATAA                           HANCESTRO:0590   
...                                                   ...   
TTCTTAGGTCATATGC                           HANCESTRO:0590   
TTGCGTCGTGATAAGT                           HANCESTRO:0590   
TTGCGTC

In [129]:
index_values = raw_nasal.obs.index.tolist()

Let's update the metadata to match Cellxgene requirements 

In [130]:
donors = raw_nasal.obs['orig.ident'].unique()
print(donors)

['BU_L1', 'BU_R1', 'KA_left', 'KA_right', 'LH_0012', 'LH_2077', 'LH_0034', 'LH_0951_cellRanger', 'LH_1925_cellRanger']
Categories (9, object): ['BU_L1', 'BU_R1', 'KA_left', 'KA_right', ..., 'LH_0034', 'LH_0951_cellRanger', 'LH_1925_cellRanger', 'LH_2077']


In [131]:
update_df = pd.DataFrame({
    'orig.ident': ["BU_L1", "BU_R1", "KA_left", "KA_right",
                   "LH_0012", "LH_2077", "LH_0034", "LH_0951_cellRanger",
                   "LH_1925_cellRanger"],
    'age': ['30','30','34','34','63','65','64','66','59'],
    'smoking_status': ["Never","Never","Unknown","Unknown","Former","Former","Former","Current","Current"],
    'development_stage_ontology_term_id': ["HsapDv:0000238","HsapDv:0000238","HsapDv:0000238","HsapDv:0000238",
                                           "HsapDv:0000241","HsapDv:0000241","HsapDv:0000241","HsapDv:0000241",
                                           "HsapDv:0000240"],
    'sex_ontology_term_id': ["PATO:0000384","PATO:0000384","PATO:0000383","PATO:0000383","PATO:0000384","PATO:0000383","PATO:0000384","PATO:0000384","PATO:0000384"],
    "self_reported_ethnicity_ontology_term_id": ["HANCESTRO:0590","HANCESTRO:0590","HANCESTRO:0008","HANCESTRO:0008","HANCESTRO:0590",
                                                 "HANCESTRO:0590","HANCESTRO:0590","HANCESTRO:0590","HANCESTRO:0590"]
})

In [132]:
raw_nasal.obs = raw_nasal.obs.merge(update_df, on='orig.ident', how='left')

Some samples included in this object are missing from the paper? What do I do with those? 
<br>
Also unclear about disease ontology ID, samples are from patients from lung cancer screeing but I put normal for now

In [134]:
raw_nasal.obs["disease_ontology_term_id"] = "PATO:0000461"
raw_nasal.obs["tissue_type"] = "tissue"
raw_nasal.obs["tissue_ontology_term_id"] = "UBERON:0005384"
raw_nasal.obs["assay_ontology_term_id"] = "EFO:0008913"
raw_nasal.obs['suspension_type'] = "cell"

Cell types: I am unsure about MUC4 NEAT1 cells, right now I put down protein secretory cells but unsure,
<br>
Also what is 1169 predominant cells?

In [21]:
cell_df = pd.DataFrame({
    'cell_type': ["Olfactory glandular cells",
                    "Transitional Cells_Basal_Club",
                    "Transitional Cells_Club_Secretory",
                    "Basal cells",
                    "Seromucous glandular Cells",
                    "Ciliated cells",
                    "Goblet cells",
                    "Club cells",
                    "Keratinizing Epithelial cells",
                    "Proliferating basal cells",
                    "T cells",
                    "Maturing ciliated cells",
                    "Ionocytes",
                    "Antigen presenting cells",
                    "Unknown",
                    "KRT15 17 Basal cells",
                    "Keratinocytes"],
    'cell_type_ontology_term_id': ["CL:0000150","CL:0002368","CL:0002368","CL:0002633","CL:0000150","CL:4030034","CL:0002480","CL:0000158",
                                   "CL:0000237","CL:0002633","CL:0000084","CL:4030034","CL:0005006","CL:0000145","CL:0002368","CL:0002633",
                                   "CL:0000312"]
})
raw_nasal.obs = raw_nasal.obs.merge(cell_df, on='cell_type', how='left')

In [135]:
raw_nasal.obs = raw_nasal.obs.rename(columns={'orig.ident':'donor_id'})

In [2]:
raw_nasal.obs['is_primary_data'] = True

In [14]:
raw_nasal.obs['organism_ontology_term_id'] = 'NCBITaxon:9606'

Let's check the metadata after updating it!

In [136]:
raw_nasal.obs.index = index_values

In [30]:
raw_nasal.obs

donor_id  nCount_RNA  nFeature_RNA  percent.mt  \
AAACCTGAGAGCCTAG               BU_L1      1604.0           732    7.481297   
AAACCTGAGATCGATA               BU_L1      5782.0          1898    8.353511   
AAACCTGAGCGATATA               BU_L1      3463.0          1390    8.489749   
AAACCTGAGCGTCAAG               BU_L1      1946.0           825    5.395683   
AAACCTGAGCTGATAA               BU_L1      1685.0           922    9.673591   
...                              ...         ...           ...         ...   
TTCTTAGGTCATATGC  LH_1925_cellRanger     29369.0          5368    4.780551   
TTGCGTCGTGATAAGT  LH_1925_cellRanger      5279.0          1708    2.292101   
TTGCGTCTCTCGCATC  LH_1925_cellRanger     25460.0          4282    0.816968   
TTGTAGGGTTACGACT  LH_1925_cellRanger     24188.0          5258    2.947743   
TTTGGTTTCGCCATAA  LH_1925_cellRanger     18904.0          4039    2.020736   

                  integrated_snn_res.1.2  seurat_clusters  \
AAACCTGAGAGCCTAG                       1                1   
AAACCTGAGATCGATA                       1                1   
AAACCTGAGCGATATA                       9                9   
AAACCTGAGCGTCAAG                       2                2   
AAACCTGAGCTGATAA                       1                1   
...                                  ...              ...   
TTCTTAGGTCATATGC                       0                0   
TTGCGTCGTGATAAGT                       1                1   
TTGCGTCTCTCGCATC                      12               12   
TTGTAGGGTTACGACT                       0                0   
TTTGGTTTCGCCATAA                       9                9   

                                          cell_type age smoking_status  \
AAACCTGAGAGCCTAG          Olfactory glandular cells  30          Never   
AAACCTGAGATCGATA          Olfactory glandular cells  30          Never   
AAACCTGAGCGATATA      Transitional Cells_Basal_Club  30          Never   
AAACCTGAGCGTCAAG  Transitional Cells_Club_Secretory  30          Never   
AAACCTGAGCTGATAA          Olfactory glandular cells  30          Never   
...                                             ...  ..            ...   
TTCTTAGGTCATATGC                       Goblet cells  59        Current   
TTGCGTCGTGATAAGT          Olfactory glandular cells  59        Current   
TTGCGTCTCTCGCATC                        Basal cells  59        Current   
TTGTAGGGTTACGACT                       Goblet cells  59        Current   
TTTGGTTTCGCCATAA      Transitional Cells_Basal_Club  59        Current   

                 development_stage_ontology_term_id sex_ontology_term_id  \
AAACCTGAGAGCCTAG                     HsapDv:0000238         PATO:0000384   
AAACCTGAGATCGATA                     HsapDv:0000238         PATO:0000384   
AAACCTGAGCGATATA                     HsapDv:0000238         PATO:0000384   
AAACCTGAGCGTCAAG                     HsapDv:0000238         PATO:0000384   
AAACCTGAGCTGATAA                     HsapDv:0000238         PATO:0000384   
...                                             ...                  ...   
TTCTTAGGTCATATGC                     HsapDv:0000240         PATO:0000384   
TTGCGTCGTGATAAGT                     HsapDv:0000240         PATO:0000384   
TTGCGTCTCTCGCATC                     HsapDv:0000240         PATO:0000384   
TTGTAGGGTTACGACT                     HsapDv:0000240         PATO:0000384   
TTTGGTTTCGCCATAA                     HsapDv:0000240         PATO:0000384   

                 self_reported_ethnicity_ontology_term_id  \
AAACCTGAGAGCCTAG                           HANCESTRO:0590   
AAACCTGAGATCGATA                           HANCESTRO:0590   
AAACCTGAGCGATATA                           HANCESTRO:0590   
AAACCTGAGCGTCAAG                           HANCESTRO:0590   
AAACCTGAGCTGATAA                           HANCESTRO:0590   
...                                                   ...   
TTCTTAGGTCATATGC                           HANCESTRO:0590   
TTGCGTCGTGATAAGT                           HANCESTRO:0590   
TTGCGTC

## Reductions

Let's load in pca

In [138]:
pca_matrix = pd.read_csv("pca_matrix.csv", index_col=0)  
pca_loadings = pd.read_csv("pca_loadings.csv", index_col=0)
raw_nasal.obsm['X_pca'] = pca_matrix

In [139]:
raw_nasal.uns['PCs'] = pca_loadings

All pca cell embeddings and feature loadings are in
<br>
Umap is also in

In [140]:
raw_nasal.uns['pca_stdev'] = [
    12.582192, 5.765848, 5.345841, 4.215733, 3.995945, 3.411001, 3.198764, 
    3.080030, 2.977143, 2.783367, 2.737464, 2.360888, 2.186780, 2.054993, 
    2.031383, 1.938378, 1.813532, 1.738787, 1.668937, 1.624730, 1.618633, 
    1.596963, 1.529886, 1.518697, 1.495440, 1.484925, 1.467325, 1.434269, 
    1.418645, 1.405264
]

Let's add in umap as well

In [4]:
umap_matrix = pd.read_csv("nose_umap_matrix.csv", index_col=0)
raw_nasal.obsm['X_umap'] = umap_matrix

In [6]:
raw_nasal.obsm['X_umap']

UMAP_1    UMAP_2
AAACCTGAGAGCCTAG  0.433861  4.782102
AAACCTGAGATCGATA -0.122517  5.356254
AAACCTGAGCGATATA  3.004606 -1.958560
AAACCTGAGCGTCAAG -1.374543  0.777606
AAACCTGAGCTGATAA -1.489678  6.217160
...                    ...       ...
TTCTTAGGTCATATGC  5.731987  4.725253
TTGCGTCGTGATAAGT -0.568246  4.859620
TTGCGTCTCTCGCATC  2.503363 -5.091516
TTGTAGGGTTACGACT  6.458843  4.555409
TTTGGTTTCGCCATAA  4.102743 -4.021431

[34833 rows x 2 columns]

## Graphs

We now need to get in the nn and snn graphs 

In [44]:
raw_nasal.obsp.clear()

In [141]:
from scipy.io import mmread
nn_sparse = mmread('rawnasal_nn.mtx')
snn_sparse = mmread('rawnasal_snn.mtx')
csr_nn = csr_matrix(nn_sparse)
csr_snn = csr_matrix(snn_sparse)
raw_nasal.obsp['nn'] = csr_nn
raw_nasal.obsp['snn'] = csr_snn

Let's make sure they are correct

In [142]:
densesnn = raw_nasal.obsp['snn'].toarray()
print(densesnn)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


## Ensembl IDs

Let's put in ensembl IDs as the index of var

In [4]:
ensembl = pd.read_csv('features.tsv', sep='\t', header=0)

# Step 2: Append the column names as the first row
columns_as_row = pd.DataFrame([ensembl.columns], columns=ensembl.columns)
ensembl = pd.concat([columns_as_row, ensembl], ignore_index=True)

# Step 3: Reset the column names so they are standard (numeric indices)
ensembl.columns = range(ensembl.shape[1])

# Step 4: Ensure there are no duplicates or null values in the index column (first column)
ensembls = ensembl.iloc[:, 0] 

raw_nasal.var.index = ensembls
raw_nasal.var.index.name = 'Ensembl_IDs'

In [5]:
raw_nasal.raw.var.index = ensembls
raw_nasal.raw.var.index.name = 'Ensembl_IDs'

In [79]:
raw_nasal.var.reset_index(drop=True, inplace=True)

Last Check!!!

In [6]:
raw_nasal

AnnData object with n_obs × n_vars = 34833 × 33694
    obs: 'donor_id', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'integrated_snn_res.1.2', 'seurat_clusters', 'cell_type', 'age', 'smoking_status', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'cell_type_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'assay_ontology_term_id', 'suspension_type', 'is_primary_data'
    var: 'features'
    uns: 'PCs', 'pca_stdev', 'title'
    obsm: 'X_pca', 'X_umap'
    obsp: 'nn', 'snn'

In [11]:
raw_nasal.raw.var

features
Ensembl_IDs                  
ENSG00000243485  RP11-34P13.3
ENSG00000237613       FAM138A
ENSG00000186092         OR4F5
ENSG00000238009  RP11-34P13.7
ENSG00000239945  RP11-34P13.8
...                       ...
ENSG00000277856    AC233755.2
ENSG00000275063    AC233755.1
ENSG00000271254    AC240274.1
ENSG00000277475    AC213203.1
ENSG00000268674       FAM231B

[33694 rows x 1 columns]

## Validation Add-ons

In [34]:
# Check for NaN values in the 'cell_type_ontology_term_id' column of adata.obs
nan_rows = raw_nasal.obs[raw_nasal.obs['cell_type_ontology_term_id'].isna()]

# Display rows with NaN values
print(nan_rows)


Empty DataFrame
Columns: [donor_id, nCount_RNA, nFeature_RNA, percent.mt, integrated_snn_res.1.2, seurat_clusters, cell_type, age, smoking_status, development_stage_ontology_term_id, sex_ontology_term_id, self_reported_ethnicity_ontology_term_id, cell_type_ontology_term_id, disease_ontology_term_id, tissue_type, tissue_ontology_term_id, assay_ontology_term_id, suspension_type, is_primary_data, organism_ontology_term_id]
Index: []


In [35]:
nan_final_celltype = nan_rows['cell_type']
print(nan_final_celltype)

Series([], Name: cell_type, dtype: category
Categories (17, object): ['Antigen presenting cells', 'Basal cells', 'Ciliated cells', 'Club cells', ..., 'T cells', 'Transitional Cells_Basal_Club', 'Transitional Cells_Club_Secretory', 'Unknown'])


In [33]:
# Replace "ciliated cells" with "maturing ciliated cells" in the 'cell_type' column
raw_nasal.obs['cell_type'] = raw_nasal.obs['cell_type'].replace("Matuaring ciliated cells", "Maturing ciliated cells")
raw_nasal.obs['cell_type_ontology_term_id'] = raw_nasal.obs['cell_type_ontology_term_id'].fillna("CL:4030034")


## Submission errors fix

In [10]:
raw_nasal.obs

donor_id  nCount_RNA  nFeature_RNA  percent.mt  \
AAACCTGAGAGCCTAG               BU_L1      1604.0           732    7.481297   
AAACCTGAGATCGATA               BU_L1      5782.0          1898    8.353511   
AAACCTGAGCGATATA               BU_L1      3463.0          1390    8.489749   
AAACCTGAGCGTCAAG               BU_L1      1946.0           825    5.395683   
AAACCTGAGCTGATAA               BU_L1      1685.0           922    9.673591   
...                              ...         ...           ...         ...   
TTCTTAGGTCATATGC  LH_1925_cellRanger     29369.0          5368    4.780551   
TTGCGTCGTGATAAGT  LH_1925_cellRanger      5279.0          1708    2.292101   
TTGCGTCTCTCGCATC  LH_1925_cellRanger     25460.0          4282    0.816968   
TTGTAGGGTTACGACT  LH_1925_cellRanger     24188.0          5258    2.947743   
TTTGGTTTCGCCATAA  LH_1925_cellRanger     18904.0          4039    2.020736   

                  integrated_snn_res.1.2  seurat_clusters  \
AAACCTGAGAGCCTAG                       1                1   
AAACCTGAGATCGATA                       1                1   
AAACCTGAGCGATATA                       9                9   
AAACCTGAGCGTCAAG                       2                2   
AAACCTGAGCTGATAA                       1                1   
...                                  ...              ...   
TTCTTAGGTCATATGC                       0                0   
TTGCGTCGTGATAAGT                       1                1   
TTGCGTCTCTCGCATC                      12               12   
TTGTAGGGTTACGACT                       0                0   
TTTGGTTTCGCCATAA                       9                9   

                                          cell_type age smoking_status  \
AAACCTGAGAGCCTAG          Olfactory glandular cells  30          Never   
AAACCTGAGATCGATA          Olfactory glandular cells  30          Never   
AAACCTGAGCGATATA      Transitional Cells_Basal_Club  30          Never   
AAACCTGAGCGTCAAG  Transitional Cells_Club_Secretory  30          Never   
AAACCTGAGCTGATAA          Olfactory glandular cells  30          Never   
...                                             ...  ..            ...   
TTCTTAGGTCATATGC                       Goblet cells  59        Current   
TTGCGTCGTGATAAGT          Olfactory glandular cells  59        Current   
TTGCGTCTCTCGCATC                        Basal cells  59        Current   
TTGTAGGGTTACGACT                       Goblet cells  59        Current   
TTTGGTTTCGCCATAA      Transitional Cells_Basal_Club  59        Current   

                 development_stage_ontology_term_id sex_ontology_term_id  \
AAACCTGAGAGCCTAG                     HsapDv:0000124         PATO:0000384   
AAACCTGAGATCGATA                     HsapDv:0000124         PATO:0000384   
AAACCTGAGCGATATA                     HsapDv:0000124         PATO:0000384   
AAACCTGAGCGTCAAG                     HsapDv:0000124         PATO:0000384   
AAACCTGAGCTGATAA                     HsapDv:0000124         PATO:0000384   
...                                             ...                  ...   
TTCTTAGGTCATATGC                     HsapDv:0000153         PATO:0000384   
TTGCGTCGTGATAAGT                     HsapDv:0000153         PATO:0000384   
TTGCGTCTCTCGCATC                     HsapDv:0000153         PATO:0000384   
TTGTAGGGTTACGACT                     HsapDv:0000153         PATO:0000384   
TTTGGTTTCGCCATAA                     HsapDv:0000153         PATO:0000384   

                 self_reported_ethnicity_ontology_term_id  \
AAACCTGAGAGCCTAG                           HANCESTRO:0590   
AAACCTGAGATCGATA                           HANCESTRO:0590   
AAACCTGAGCGATATA                           HANCESTRO:0590   
AAACCTGAGCGTCAAG                           HANCESTRO:0590   
AAACCTGAGCTGATAA                           HANCESTRO:0590   
...                                                   ...   
TTCTTAGGTCATATGC                           HANCESTRO:0590   
TTGCGTCGTGATAAGT                           HANCESTRO:0590   
TTGCGTC

In [5]:
raw_nasal.obs['assay_ontology_term_id'] = 'EFO:0009899'

In [7]:
age = ['30','30','34','34','63','65','64','66','59']
development_stage_ontology_term_id = ['HsapDv:0000124','HsapDv:0000124','HsapDv:0000128','HsapDv:0000128',
                                      'HsapDv:0000157','HsapDv:0000159','HsapDv:0000158','HsapDv:0000160',
                                      'HsapDv:0000153']

age_to_ontology = dict(zip(age, development_stage_ontology_term_id))

raw_nasal.obs["development_stage_ontology_term_id"] = raw_nasal.obs["age"].map(age_to_ontology)

In [8]:
raw_nasal.obs['development_stage_ontology_term_id']

AAACCTGAGAGCCTAG    HsapDv:0000124
AAACCTGAGATCGATA    HsapDv:0000124
AAACCTGAGCGATATA    HsapDv:0000124
AAACCTGAGCGTCAAG    HsapDv:0000124
AAACCTGAGCTGATAA    HsapDv:0000124
                         ...      
TTCTTAGGTCATATGC    HsapDv:0000153
TTGCGTCGTGATAAGT    HsapDv:0000153
TTGCGTCTCTCGCATC    HsapDv:0000153
TTGTAGGGTTACGACT    HsapDv:0000153
TTTGGTTTCGCCATAA    HsapDv:0000153
Name: development_stage_ontology_term_id, Length: 34833, dtype: category
Categories (7, object): ['HsapDv:0000124', 'HsapDv:0000128', 'HsapDv:0000153', 'HsapDv:0000157', 'HsapDv:0000158', 'HsapDv:0000159', 'HsapDv:0000160']

In [9]:
raw_nasal.obs['age']

AAACCTGAGAGCCTAG    30
AAACCTGAGATCGATA    30
AAACCTGAGCGATATA    30
AAACCTGAGCGTCAAG    30
AAACCTGAGCTGATAA    30
                    ..
TTCTTAGGTCATATGC    59
TTGCGTCGTGATAAGT    59
TTGCGTCTCTCGCATC    59
TTGTAGGGTTACGACT    59
TTTGGTTTCGCCATAA    59
Name: age, Length: 34833, dtype: category
Categories (7, object): ['30', '34', '59', '63', '64', '65', '66']